### ISSUE TITLE
PRÁCTICA 9 - PROYECTO Y SEGUIMIENTO EQUIPO YECJ

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-equipo-ycej#1]
[PRACTICA.9.-.PROYECTO.Y.SEGUIMIENTO.EQUIPO.YECJ.pdf](https://github.com/user-attachments/files/17547680/PRACTICA.9.-.PROYECTO.Y.SEGUIMIENTO.EQUIPO.YECJ.pdf)

**https://github.com/SistemasTecTlaxiaco/Destello-Movil**

**Comment by Nelsy21** [comment]
Portada: 25 puntos
Describe el procedimiento: 25 puntos
Incluye ilustraciones y capturas: 25 puntos
Conclusión: 25 puntos
Puntaje alcanzado 100% = 20 puntos

**Comment by josealfredo79** [comment]
bien hecho y revisado...falta el link de su proyecto

**Comment by yanet-02** [comment]
https://github.com/orgs/SistemasTecTlaxiaco/projects/101/views/1
